services:
  # Backend API Service
  - type: web
    name: ecommerce-arbitrage-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: BLUECART_API_KEY
        sync: false
      - key: RAINFOREST_API_KEY
        sync: false
      - key: BIGBOX_API_KEY
        sync: false
