services:
  # Backend API Service
  - type: web
    name: extension-marketplace-api-2-0
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: BLUECART_API_KEY
        sync: false
      - key: RAINFOREST_API_KEY
        sync: false
      - key: BIGBOX_API_KEY
        sync: false
